import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { getServerSession } from "next-auth";

import SessionProvider from "@/components/SessionProvider";
import { Toaster } from "react-hot-toast";
import { cn } from "@/lib/utils";

const fontSans = FontSans({ 
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={cn("bg-background font-sans antialiased", fontSans.variable)}>
        <SessionProvider>
          <main className="max-w-full bg-slate-950 text-2xl flex gap-2">
            <Toaster position="top-center" />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
