export const albumIdx: {[key: string]: number} = {
    "Taylor Swift": 0,
    "Fearless": 1,
    "Speak Now": 2,
    "Red": 3,
    "1989": 4,
    "Reputation": 5,
    "Lover": 6,
    "folklore": 7,
    "evermore": 8,
    "Midnights": 9,
}

export const songsToAlbums: {[key: string]: string} = {
    "Welcome To New York (Taylor's Version)": "1989",
    "Blank Space (Taylor's Version)": "1989",
    "Style (Taylor's Version)": "1989",
    "Out Of The Woods (Taylor's Version)": "1989",
    "All You Had To Do Was Stay (Taylor's Version)": "1989",
    "Shake It Off (Taylor's Version)": "1989",
    "I Wish You Would (Taylor's Version)": "1989",
    "Bad Blood (Taylor's Version)": "1989",
    "Wildest Dreams (Taylor's Version)": "1989",
    "How You Get The Girl (Taylor's Version)": "1989",
    "This Love (Taylor's Version)": "1989",
    "I Know Places (Taylor's Version)": "1989",
    "Clean (Taylor's Version)": "1989",
    "Wonderland (Taylor's Version)": "1989",
    "You Are In Love (Taylor's Version)": "1989",
    "New Romantics (Taylor's Version)": "1989",
    "\"Slut!\" (Taylor's Version) (From The Vault)": "1989",
    "Say Don't Go (Taylor's Version) (From The Vault)": "1989",
    "Now That We Don't Talk (Taylor's Version) (From The Vault)": "1989",
    "Suburban Legends (Taylor's Version) (From The Vault)": "1989",
    "Is It Over Now? (Taylor's Version) (From The Vault)": "1989",
    "Bad Blood (feat. Kendrick Lamar) (Taylor's Version)": "1989",
    "Cruel Summer - Live from TS | The Eras Tour": "Lover",
    "Cruel Summer - LP Giobbi Remix": "Lover",
    "Mine (Taylor's Version)": "Speak Now",
    "Sparks Fly (Taylor's Version)": "Speak Now",
    "Back To December (Taylor's Version)": "Speak Now",
    "Speak Now (Taylor's Version)": "Speak Now",
    "Dear John (Taylor's Version)": "Speak Now",
    "Mean (Taylor's Version)": "Speak Now",
    "The Story Of Us (Taylor's Version)": "Speak Now",
    "Never Grow Up (Taylor's Version)": "Speak Now",
    "Enchanted (Taylor's Version)": "Speak Now",
    "Better Than Revenge (Taylor's Version)": "Speak Now",
    "Innocent (Taylor's Version)": "Speak Now",
    "Haunted (Taylor's Version)": "Speak Now",
    "Last Kiss (Taylor's Version)": "Speak Now",
    "Long Live (Taylor's Version)": "Speak Now",
    "Ours (Taylor's Version)": "Speak Now",
    "Superman (Taylor's Version)": "Speak Now",
    "Electric Touch (feat. Fall Out Boy) (Taylor's Version) (From The Vault)": "Speak Now",
    "When Emma Falls In Love (Taylor's Version) (From The Vault)": "Speak Now",
    "I Can See You (Taylor's Version) (From The Vault)": "Speak Now",
    "Castles Crumbling (feat. Hayley Williams) (Taylor's Version) (From The Vault)": "Speak Now",
    "Foolish One (Taylor's Version) (From The Vault)": "Speak Now",
    "Timeless (Taylor's Version) (From The Vault)": "Speak Now",
    "You're Losing Me (From The Vault)": "Midnights",
    "Karma (feat. Ice Spice)": "Midnights",
    "Hits Different": "Midnights",
    "Snow On The Beach (feat. More Lana Del Ray)": "Midnights",
    "Karma": "Midnights",
    "Lavender Haze": "Midnights",
    "Safe & Sound (feat. Joy Williams and John Paul White) (Taylor's Version)": "Red",
    "Anti-Hero": "Midnights",
    "Lavender Haze - Acoustic Version": "Midnights",
    "Eyes Open (Taylor's Version)": "Red",
    "If This Was A Movie (Taylor's Version)": "Fearless",
    "Lavender Haze - Snakehips Remix": "Midnights",
    "Lavender Haze - Tensnake Remix": "Midnights",
    "Lavender Haze - Jungle Remix": "Midnights",
    "Lavender Haze - Felix Jaehn Remix": "Midnights",
    "Anti-Hero - ILLENIUM Remix": "Midnights",
    "Anti-Hero - Acoustic Version": "Midnights",
    "Anti-Hero (feat. Bleachers)": "Midnights",
    "Anti-Hero - Roosevelt Remix": "Midnights",
    "Anti-Hero - Kungs Remix": "Midnights",
    "Anti-Hero - Jayda G Remix": "Midnights",
    "Maroon": "Midnights",
    "Snow On The Beach (feat. Lana Del Ray)": "Midnights",
    "You're On Your Own, Kid": "Midnights",
    "Midnight Rain": "Midnights",
    "Question...?": "Midnights",
    "Vigilante Shit": "Midnights",
    "Bejewled": "Midnights",
    "Labyrinth": "Midnights",
    "Sweet Nothing": "Midnights",
    "Mastermind": "Midnights",
    "The Great War": "Midnights",
    "Bigger Than The Whole Sky": "Midnights",
    "Paris": "Midnights",
    "High Infidelity": "Midnights",
    "Glitch": "Midnights",
    "Would've, Could've, Should've": "Midnights",
    "Dear Reader": "Midnights",
    "Carolina - From The Motion Picture \"Where The Crawdads Sing\"": "Other",
    "Carolina - \"Where The Crawdads Sing\" - Video Edition": "Other",
    "All Too Well (10 Minute Version) (The Short Film)": "Red",
    "The Joker And The Queen (feat. Taylor Swift)": "Features",
    "Message In A Bottle (Fat Max G Remix) (Taylor's Version)": "Red",
    "All Too Well (Sad Girl Autumn Version) - Recorded At Long Pond Studios": "Red",
    "Message In A Bottle (Taylor's Version) (From The Vault)": "Red",
    "Run (feat. Ed Sheeran) (Taylor's Version) (From The Vault)": "Red",
    "I Bet You Think About Me (feat. Chris Stapleton) (Taylor's Version) (From The Vault)": "Red",
    "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)": "Red",
    "Nothing New (feat. Phoebe Bridgers) (Taylor's Version) (From The Vault)": "Red",
    "Forever Winter (Taylor's Version) (From The Vault)": "Red",
    "Babe (Taylor's Version) (From The Vault)": "Red",
    "Better Man (Taylor's Version) (From The Vault)": "Red",
    "The Very First Night (Taylor's Version) (From The Vault)": "Red",
    "State Of Grace (Taylor's Version)": "Red",
    "Red (Taylor's Version)": "Red",
    "Treacherous (Taylor's Version)": "Red",
    "I Knew You Were Trouble (Taylor's Version)": "Red",
    "All Too Well (Taylor's Version)": "Red",
    "22 (Taylor's Version)": "Red",
    "I Almost Do (Taylor's Version)": "Red",
    "We Are Never Ever Getting Back Together (Taylor's Version)": "Red",
    "Stay Stay Stay (Taylor's Version)": "Red",
    "The Last Time (feat. Gary Lightbody of Snow Patrol) (Taylor's Version)": "Red",
    "Holy Ground (Taylor's Version)": "Red",
    "Sad Beautiful Tragic (Taylor's Version)": "Red",
    "The Lucky One (Taylor's Version)": "Red",
    "Everything Has Changed (feat. Ed Sheeran) (Taylor's Version)": "Red",
    "Starlight (Taylor's Version)": "Red",
    "Begin Again (Taylor's Version)": "Red",
    "The Moment I Knew (Taylor's Version)": "Red",
    "Come Back...Be Here (Taylor's Version)": "Red",
    "Girl At Home (Taylor's Version)": "Red",
    "State Of Grace (Acoustic Version) (Taylor's Version)": "Red",
    "Ronan (Taylor's Version)": "Red",
    "Renegade (feat. Taylor Swift)": "Features",
    "Fearless (Taylor's Version)": "Fearless",
    "Fifteen (Taylor's Version)": "Fearless",
    "Love Story (Taylor's Version": "Fearless",
    "Hey Stephen (Taylor's Version)": "Fearless",
    "White Horse (Taylor's Version)": "Fearless",
    "You Belong With Me (Taylor's Version)": "Fearless",
    "Breathe (feat. Colbie Caillat) (Taylor's Version)": "Fearless",
    "Tell Me Why (Taylor's Version)": "Fearless",
    "You're Not Sorry (Taylor's Version)": "Fearless",
    "The Way I Loved You (Taylor's Version)": "Fearless",
    "Forever & Always (Taylor's Version)": "Fearless",
    "The Best Day (Taylor's Version)": "Fearless",
    "Change (Taylor's Version)": "Fearless",
    "Jump Then Fall (Taylor's Version)": "Fearless",
    "Untouchable (Taylor's Version)": "Fearless",
    "Forever & Always (Piano Version) (Taylor's Version)": "Fearless",
    "Come In With The Rain (Taylor's Version)": "Fearless",
    "Superstar (Taylor's Version)": "Fearless",
    "The Other Side Of The Door (Taylor's Version)": "Fearless",
    "Today Was A Fairytale (Taylor's Version)": "Fearless",
    "You All Over Me (feat. Maren Morris) (Taylor's Version) (From The Vault)": "Fearless",
    "Mr. Perfectly Fine (Taylor's Version) (From The Vault)": "Fearless",
    "We Were Happy (Taylor's Version) (From The Vault)": "Fearless",
    "That's When (feat. Keith Urban) (Taylor's Version) (From The Vault)": "Fearless",
    "Don't You (Taylor's Version) (From The Vault)": "Fearless",
    "Bye Bye Baby (Taylor's Version) (From The Vault)": "Fearless",
    "willow - moonlit witch version": "evermore",
    "willow - lonely witch version": "evermore",
    "willow - dancing witch version (Elvira remix)": "evermore",
    "willow": "evermore",
    "champagne problems": "evermore",
    "gold rush": "evermore",
    "'tis the damn deason": "evermore",
    "tolerate it": "evermore",
    "no body, no crime (feat. HAIM)": "evermore",
    "happiness": "evermore",
    "dorothea": "evermore",
    "coney island (feat. The National)": "evermore",
    "wilivylow": "evermore",
    "cowboy like me": "evermore",
    "long story short": "evermore",
    "marjorie": "evermore",
    "closure": "evermore",
    "evermore (feat. Bon Iver)": "evermore",
    "right where you left me - bonus track": "evermore",
    "it's time to go - bonus track": "evermore",
    "the 1": "folklore",
    "cardigan": "folklore",
    "the last great american dynasty": "folklore",
    "exile (feat. Bon Iver)": "folklore",
    "my tears ricochet": "folklore",
    "mirrorball": "folklore",
    "seven": "folklore",
    "august": "folklore",
    "this is me trying": "folklore",
    "illicit affairs": "folklore",
    "invisible string": "folklore",
    "mad woman": "folklore",
    "epiphany": "folklore",
    "betty": "folklore",
    "peace": "folklore",
    "hoax": "folklore",
    "the lakes - bonus track": "folklore",
    "the lakes - original version": "folklore",
    "cardigan - cabin in candlelight version": "folklore",
    "the 1 - the long pond studio sessions": "folklore",
    "cardigan - the long pond studio sessions": "folklore",
    "the last great american dynasty - the long pond studio sessions": "folklore",
    "exile (feat. Bon Iver) - the long pond studio sessions": "folklore",
    "my tears ricochet - the long pond studio sessions": "folklore",
    "mirrorball - the long pond studio sessions": "folklore",
    "seven - the long pond studio sessions": "folklore",
    "august - the long pond studio sessions": "folklore",
    "this is me trying - the long pond studio sessions": "folklore",
    "illicit affairs - the long pond studio sessions": "folklore",
    "invisible string - the long pond studio sessions": "folklore",
    "mad woman - the long pond studio sessions": "folklore",
    "epiphany - the long pond studio sessions": "folklore",
    "betty - the long pond studio sessions": "folklore",
    "peace - the long pond studio sessions": "folklore",
    "hoax - the long pond studio sessions": "folklore",
    "the lakes - the long pond studio sessions": "folklore",
    "Me! - Live From Paris": "Lover",
    "The Archer - Live From Paris": "Lover",
    "Death By A Thousand Cuts - Live From Paris": "Lover",
    "Cornelia Street - Live From Paris": "Lover",
    "The Man - Live From Paris": "Lover",
    "Daylight - Live From Paris": "Lover",
    "You Need To Calm Down - Live From Paris": "Lover",
    "Lover - Live From Paris": "Lover",
    "I Forgot That You Existed": "Lover",
    "Cruel Summer": "Lover",
    "Lover": "Lover",
    "The Man": "Lover",
    "The Archer": "Lover",
    "I Think He Knows": "Lover",
    "Miss Americana & The Heartbreak Prince": "Lover",
    "Paper Rings": "Lover",
    "Cornelia Street": "Lover",
    "Death By A Thousand Cuts": "Lover",
    "London Boy": "Lover",
    "Soon You'll Get Better (feat. Tne Chicks)": "Lover",
    "False God": "Lover",
    "You Need To Calm Down": "Lover",
    "Afterglow": "Lover",
    "Me! (feat. Brandon Urie of Panic! At The Disco)": "Lover",
    "It's Nice To Have A Friend": "Lover",
    "Daylight": "Lover",
    "All Of The Girls You Loved Before": "Lover",
}